### ISSUE TITLE
The necessity of one more level inside tutorials/

### ISSUE THREAD

**Issue by iocoder** [zxasm/z80#3]
Is it necessary to have tutorials/facebook/partX instead of just tutorials/partX? I feel that the 'facebook' directory level is not very necessary, and getting rid of it saves navigation time for terminal users.

**Comment by adrianpbrown** [comment]
Im happy to drop facebook – it was only in that folder for my local directory structure for my own project reasons

**Comment by zxasm** [comment]
So what happens if other tutorials are created?

**Comment by zxasm** [comment]
ie. 
tutorials/screen/partx
tutorials/keyboard/partx 

etc...

**Comment by adrianpbrown** [comment]
Hmm good point probably should go to tutorials\adrianbrown\facebook\part1 or something like that

**Comment by zxasm** [comment]
Yep, that sounds good to me.

tutorials\<submitter>\<topic>\ ...

**Comment by iocoder** [comment]
Thanks guys!
